title: Praniti Khurana
description: Portfolio, notes, and a running catalog of books
url: "https://pranitikhurana.com"

header_pages:
  - blog.md
  - reading-list.md

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "_posts"
    values:
      layout: "post"
